version: '3.7'

services:
  # web: 
  #   image: awlui2019/docker_setup:latest
  #   expose:
  #     - 8000
  # web2:
  #   build: ./app2/djangoStarter2
  #   expose:
  #     - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data: